<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Stereooboi</title>
        <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Это Header</h2>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "index",
                        "action" => "index"
                    ),null,TRUE)?>">
                    Экообои
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "catalogue",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Каталог
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "how-to-buy",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Как купить
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "gallery",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Галерея
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "contacts",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Контакты
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "patternmaker",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Patternmaker
                </a>
                <a href="
                    <?php echo $this->url(array(
                        "controller" => "admin",
                        "action" => "index"
                    ),null,TRUE) ?>">
                    Админка
                </a>
            </div>
            <div class="content">
                <?php echo $this->layout()->content ?>
            </div>

            
        </div>



    </body>
</html>