<h1>
    Администрация
</h1>
<div>
    <a href="<?php echo $this->url(array( "action" => "add-new-entry")) ?>">Добавить новый продукт</a>
    <a href="/auth/logout">Выйти из админки</a>
</div>
<?php
foreach ($this->products as $product)
{
?>
 
<div class="product">
    <p> 
        ID: <?php echo $this->escape($product->getId()) ?><br>
        Наименование: <?php echo $this->escape($product->getName()) ?><br>
        Количество на складе: <?php echo $this->escape($product->getAmount()) ?><br>
        Описание: <?php echo $this->escape($product->getDescription()) ?></br>
        Расположение фотографии: <?php echo $this->escape($product->getFoto())?></br>
        Фото: <img src="..<?php echo $this->escape($product->getFoto())?>" alt="Фото продукта">
    </p>
    <a href="<?php echo $this->url(array(
            "controller" => "admin",
            "action" => "change-product",
            "id"     => $product->getId()))
    
    ?>">Изменить запись</a>
    <a href="<?php echo $this->url(array(
            "action" => "del-product",
            "id" => $product->getId()
        ));
        ?>" style="padding-left: 350px">Удалить запись</a>
</div>

<?php  
}